import { useApi } from '@/hooks/useApi'
import { RefreshCw, Download, FileText, CreditCard, Award, BookOpen, GraduationCap, FileCheck, AlertCircle } from 'lucide-react'
import { cn } from '@/lib/utils'

const documentTypes = [
  { id: 'admission', label: 'Admission Letter', icon: FileText, color: 'bg-blue-500/15 text-blue-400' },
  { id: 'id-card', label: 'Student ID Card', icon: CreditCard, color: 'bg-green-500/15 text-green-400' },
  { id: 'bonafide', label: 'Bonafide Certificate', icon: Award, color: 'bg-purple-500/15 text-purple-400' },
  { id: 'character', label: 'Character Certificate', icon: BookOpen, color: 'bg-amber-500/15 text-amber-400' },
  { id: 'transcript', label: 'Academic Transcript', icon: GraduationCap, color: 'bg-indigo-500/15 text-indigo-400' },
  { id: 'receipts', label: 'Fee Receipts', icon: FileCheck, color: 'bg-teal-500/15 text-teal-400' },
]

export function StudentDocuments() {
  const { data: profile, loading, error, refetch } = useApi<any>('/student/profile')

  if (loading) return <div className="flex items-center justify-center h-96"><RefreshCw className="w-8 h-8 text-indigo-500 animate-spin" /></div>
  if (error) return (
    <div className="flex flex-col items-center justify-center h-96 gap-4">
      <AlertCircle className="h-12 w-12 text-red-500" />
      <p className="text-lg text-slate-300">{error}</p>
      <button onClick={refetch} className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm">Retry</button>
    </div>
  )

  const p = profile || {}

  const handleDownload = (docType: string, label: string) => {
    let content = `${label.toUpperCase()}\n${'='.repeat(40)}\n\n`
    content += `Student Name: ${p.personal?.name || 'N/A'}\n`
    content += `Admission Number: ${p.personal?.admissionNumber || 'N/A'}\n`
    content += `Course: ${p.academic?.course || 'N/A'}\n`
    content += `Department: ${p.academic?.department || 'N/A'}\n`
    content += `Date: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}\n\n`

    if (docType === 'admission') {
      content += `This is to certify that ${p.personal?.name || 'the student'} has been admitted to ${p.academic?.course || 'the course'} at this institution.\n`
    } else if (docType === 'id-card') {
      content += `Student ID: ${p.personal?.admissionNumber || 'N/A'}\nRoll Number: ${p.academic?.rollNumber || 'N/A'}\n`
    } else if (docType === 'bonafide') {
      content += `This is to certify that ${p.personal?.name || 'the student'} is a bonafide student of this institution.\n`
    } else if (docType === 'character') {
      content += `This is to certify that ${p.personal?.name || 'the student'} bears good moral character during the period of study.\n`
    } else if (docType === 'transcript') {
      content += `Academic records and grades are available in the Results section.\n`
    } else if (docType === 'receipts') {
      content += `Fee payment receipts are available in the Fees section.\n`
    }

    content += `\n${'-'.repeat(40)}\nGenerated by School ERP System\n`

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${docType}-${(p.personal?.name || 'student').replace(/\s+/g, '-').toLowerCase()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Digital Documents</h1>
        <p className="text-slate-400 text-sm">Access and download your institutional documents</p>
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-700 p-6">
        <h2 className="text-sm font-medium text-slate-300 mb-4">Student Information</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          <div><p className="text-slate-400">Name</p><p className="font-medium text-white">{p.personal?.name}</p></div>
          <div><p className="text-slate-400">Admission No</p><p className="font-medium text-white">{p.personal?.admissionNumber}</p></div>
          <div><p className="text-slate-400">Course</p><p className="font-medium text-white">{p.academic?.course}</p></div>
          <div><p className="text-slate-400">Department</p><p className="font-medium text-white">{p.academic?.department}</p></div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {documentTypes.map((doc) => (
          <div key={doc.id} className="bg-slate-800 rounded-xl border border-slate-700 p-6 hover:border-slate-600 transition-colors">
            <div className="flex items-start gap-4">
              <div className={cn('p-3 rounded-lg', doc.color)}>
                <doc.icon className="w-6 h-6" />
              </div>
              <div className="flex-1">
                <h3 className="font-medium text-white mb-1">{doc.label}</h3>
                <p className="text-xs text-slate-400 mb-3">
                  {doc.id === 'admission' && `Admission letter for ${p.academic?.course || 'your course'}`}
                  {doc.id === 'id-card' && `Student ID: ${p.personal?.admissionNumber || 'N/A'}`}
                  {doc.id === 'bonafide' && 'Certificate of enrollment'}
                  {doc.id === 'character' && 'Character and conduct certificate'}
                  {doc.id === 'transcript' && 'Academic records and grades'}
                  {doc.id === 'receipts' && 'Fee payment receipts'}
                </p>
                <button
                  onClick={() => handleDownload(doc.id, doc.label)}
                  className="flex items-center gap-1.5 text-xs font-medium text-indigo-400 hover:text-indigo-300"
                >
                  <Download className="w-3.5 h-3.5" />Download
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-4">
        <p className="text-sm text-amber-400">
          <strong>Note:</strong> Documents are generated based on your institutional records.
          If you need corrections, please submit a request through the Helpdesk.
        </p>
      </div>
    </div>
  )
}
