-- Phase 6b: row-level security for child tables (no institutionId column).
-- Generated by src/scripts/gen-rls-child-migration.ts — do not hand-edit;
-- regenerate if the schema's parent chains change.
-- Requires the Phase 5 migration (20260928000000_rls_tenant_isolation) and the
-- `erp_app` role. Grants were already issued for ALL TABLES in Phase 5.

ALTER TABLE "public"."academic_calendar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."academic_calendar" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."academic_calendar";
CREATE POLICY "tenant_isolation" ON "public"."academic_calendar"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("academicSessionId" IN (SELECT "id" FROM "academic_sessions" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("academicSessionId" IN (SELECT "id" FROM "academic_sessions" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."activity_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."activity_logs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."activity_logs";
CREATE POLICY "tenant_isolation" ON "public"."activity_logs"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."assignment_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."assignment_submissions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."assignment_submissions";
CREATE POLICY "tenant_isolation" ON "public"."assignment_submissions"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("assignmentId" IN (SELECT "id" FROM "assignments" WHERE ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("assignmentId" IN (SELECT "id" FROM "assignments" WHERE ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."assignments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."assignments";
CREATE POLICY "tenant_isolation" ON "public"."assignments"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."attendance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."attendance";
CREATE POLICY "tenant_isolation" ON "public"."attendance"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "academicSessionId" IN (SELECT "id" FROM "academic_sessions" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "academicSessionId" IN (SELECT "id" FROM "academic_sessions" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."attendance_modes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."attendance_modes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."attendance_modes";
CREATE POLICY "tenant_isolation" ON "public"."attendance_modes"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."complaints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."complaints" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."complaints";
CREATE POLICY "tenant_isolation" ON "public"."complaints"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "ticketId" IN (SELECT "id" FROM "helpdesk_tickets" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "ticketId" IN (SELECT "id" FROM "helpdesk_tickets" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."daily_attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."daily_attendance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."daily_attendance";
CREATE POLICY "tenant_isolation" ON "public"."daily_attendance"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "attendanceModeId" IN (SELECT "id" FROM "attendance_modes" WHERE ("classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "attendanceModeId" IN (SELECT "id" FROM "attendance_modes" WHERE ("classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  );

ALTER TABLE "public"."doubt_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."doubt_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."doubt_messages";
CREATE POLICY "tenant_isolation" ON "public"."doubt_messages"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("conversationId" IN (SELECT "id" FROM "doubt_conversations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "senderId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("conversationId" IN (SELECT "id" FROM "doubt_conversations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "senderId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."employee_attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."employee_attendance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."employee_attendance";
CREATE POLICY "tenant_isolation" ON "public"."employee_attendance"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."exam_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."exam_results" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."exam_results";
CREATE POLICY "tenant_isolation" ON "public"."exam_results"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("examinationId" IN (SELECT "id" FROM "examinations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("examinationId" IN (SELECT "id" FROM "examinations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."exam_subjects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."exam_subjects" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."exam_subjects";
CREATE POLICY "tenant_isolation" ON "public"."exam_subjects"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("examinationId" IN (SELECT "id" FROM "examinations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("examinationId" IN (SELECT "id" FROM "examinations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."fee_components" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."fee_components" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."fee_components";
CREATE POLICY "tenant_isolation" ON "public"."fee_components"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("feeStructureId" IN (SELECT "id" FROM "fee_structures" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("feeStructureId" IN (SELECT "id" FROM "fee_structures" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."fee_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."fee_payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."fee_payments";
CREATE POLICY "tenant_isolation" ON "public"."fee_payments"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "feeStructureId" IN (SELECT "id" FROM "fee_structures" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "feeStructureId" IN (SELECT "id" FROM "fee_structures" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."helpdesk_comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."helpdesk_comments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."helpdesk_comments";
CREATE POLICY "tenant_isolation" ON "public"."helpdesk_comments"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("ticketId" IN (SELECT "id" FROM "helpdesk_tickets" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("ticketId" IN (SELECT "id" FROM "helpdesk_tickets" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."hostel_room_allocations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."hostel_room_allocations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."hostel_room_allocations";
CREATE POLICY "tenant_isolation" ON "public"."hostel_room_allocations"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "roomId" IN (SELECT "id" FROM "hostel_rooms" WHERE ("hostelId" IN (SELECT "id" FROM "hostels" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "buildingId" IN (SELECT "id" FROM "buildings" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "roomId" IN (SELECT "id" FROM "hostel_rooms" WHERE ("hostelId" IN (SELECT "id" FROM "hostels" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "buildingId" IN (SELECT "id" FROM "buildings" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  );

ALTER TABLE "public"."hostel_rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."hostel_rooms" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."hostel_rooms";
CREATE POLICY "tenant_isolation" ON "public"."hostel_rooms"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("hostelId" IN (SELECT "id" FROM "hostels" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "buildingId" IN (SELECT "id" FROM "buildings" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("hostelId" IN (SELECT "id" FROM "hostels" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "buildingId" IN (SELECT "id" FROM "buildings" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."leaves" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."leaves" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."leaves";
CREATE POLICY "tenant_isolation" ON "public"."leaves"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."library_issues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."library_issues" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."library_issues";
CREATE POLICY "tenant_isolation" ON "public"."library_issues"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("bookId" IN (SELECT "id" FROM "library_books" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("bookId" IN (SELECT "id" FROM "library_books" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."mcq_answers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mcq_answers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."mcq_answers";
CREATE POLICY "tenant_isolation" ON "public"."mcq_answers"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("submissionId" IN (SELECT "id" FROM "mcq_submissions" WHERE ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))) OR "questionId" IN (SELECT "id" FROM "mcq_questions" WHERE ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("submissionId" IN (SELECT "id" FROM "mcq_submissions" WHERE ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))) OR "questionId" IN (SELECT "id" FROM "mcq_questions" WHERE ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  );

ALTER TABLE "public"."mcq_questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mcq_questions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."mcq_questions";
CREATE POLICY "tenant_isolation" ON "public"."mcq_questions"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."mcq_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mcq_submissions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."mcq_submissions";
CREATE POLICY "tenant_isolation" ON "public"."mcq_submissions"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("testId" IN (SELECT "id" FROM "mcq_tests" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."parent_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."parent_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."parent_messages";
CREATE POLICY "tenant_isolation" ON "public"."parent_messages"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("conversationId" IN (SELECT "id" FROM "parent_conversations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "senderId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("conversationId" IN (SELECT "id" FROM "parent_conversations" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "senderId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."parent_students" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."parent_students" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."parent_students";
CREATE POLICY "tenant_isolation" ON "public"."parent_students"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("parentId" IN (SELECT "id" FROM "parents" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("parentId" IN (SELECT "id" FROM "parents" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."payments";
CREATE POLICY "tenant_isolation" ON "public"."payments"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("invoiceId" IN (SELECT "id" FROM "invoices" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("invoiceId" IN (SELECT "id" FROM "invoices" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."performance_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."performance_reviews" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."performance_reviews";
CREATE POLICY "tenant_isolation" ON "public"."performance_reviews"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."refresh_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."refresh_tokens" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."refresh_tokens";
CREATE POLICY "tenant_isolation" ON "public"."refresh_tokens"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."refunds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."refunds" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."refunds";
CREATE POLICY "tenant_isolation" ON "public"."refunds"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("paymentId" IN (SELECT "id" FROM "fee_payments" WHERE ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "feeStructureId" IN (SELECT "id" FROM "fee_structures" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("paymentId" IN (SELECT "id" FROM "fee_payments" WHERE ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "feeStructureId" IN (SELECT "id" FROM "fee_structures" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  );

ALTER TABLE "public"."route_stops" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."route_stops" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."route_stops";
CREATE POLICY "tenant_isolation" ON "public"."route_stops"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("routeId" IN (SELECT "id" FROM "routes" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("routeId" IN (SELECT "id" FROM "routes" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."student_scholarships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_scholarships" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."student_scholarships";
CREATE POLICY "tenant_isolation" ON "public"."student_scholarships"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "scholarshipId" IN (SELECT "id" FROM "scholarships" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "scholarshipId" IN (SELECT "id" FROM "scholarships" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."study_materials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."study_materials" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."study_materials";
CREATE POLICY "tenant_isolation" ON "public"."study_materials"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."subject_allocations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."subject_allocations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."subject_allocations";
CREATE POLICY "tenant_isolation" ON "public"."subject_allocations"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "academicSessionId" IN (SELECT "id" FROM "academic_sessions" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "academicSessionId" IN (SELECT "id" FROM "academic_sessions" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."subject_attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."subject_attendance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."subject_attendance";
CREATE POLICY "tenant_isolation" ON "public"."subject_attendance"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "timetableEntryId" IN (SELECT "id" FROM "timetable_entries" WHERE ("timetableId" IN (SELECT "id" FROM "timetables" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "courseId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))) OR "attendanceModeId" IN (SELECT "id" FROM "attendance_modes" WHERE ("classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "timetableEntryId" IN (SELECT "id" FROM "timetable_entries" WHERE ("timetableId" IN (SELECT "id" FROM "timetables" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "courseId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))) OR "attendanceModeId" IN (SELECT "id" FROM "attendance_modes" WHERE ("classId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))))
  );

ALTER TABLE "public"."timetable_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."timetable_entries" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."timetable_entries";
CREATE POLICY "tenant_isolation" ON "public"."timetable_entries"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("timetableId" IN (SELECT "id" FROM "timetables" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "courseId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("timetableId" IN (SELECT "id" FROM "timetables" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "subjectId" IN (SELECT "id" FROM "subjects" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "employeeId" IN (SELECT "id" FROM "employees" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "courseId" IN (SELECT "id" FROM "courses" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."user_notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_notifications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."user_notifications";
CREATE POLICY "tenant_isolation" ON "public"."user_notifications"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("notificationId" IN (SELECT "id" FROM "notifications" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("notificationId" IN (SELECT "id" FROM "notifications" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "studentId" IN (SELECT "id" FROM "students" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."vehicle_inspections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vehicle_inspections" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."vehicle_inspections";
CREATE POLICY "tenant_isolation" ON "public"."vehicle_inspections"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("vehicleId" IN (SELECT "id" FROM "vehicles" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("vehicleId" IN (SELECT "id" FROM "vehicles" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."vehicle_maintenances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vehicle_maintenances" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."vehicle_maintenances";
CREATE POLICY "tenant_isolation" ON "public"."vehicle_maintenances"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("vehicleId" IN (SELECT "id" FROM "vehicles" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("vehicleId" IN (SELECT "id" FROM "vehicles" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."vehicle_routes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vehicle_routes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."vehicle_routes";
CREATE POLICY "tenant_isolation" ON "public"."vehicle_routes"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("vehicleId" IN (SELECT "id" FROM "vehicles" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "routeId" IN (SELECT "id" FROM "routes" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("vehicleId" IN (SELECT "id" FROM "vehicles" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "routeId" IN (SELECT "id" FROM "routes" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );

ALTER TABLE "public"."workflow_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."workflow_actions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."workflow_actions";
CREATE POLICY "tenant_isolation" ON "public"."workflow_actions"
  FOR ALL
  USING (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("workflowId" IN (SELECT "id" FROM "workflows" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL
    OR ("workflowId" IN (SELECT "id" FROM "workflows" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')) OR "userId" IN (SELECT "id" FROM "users" WHERE "institutionId" = NULLIF(current_setting('app.current_tenant_id', true), '')))
  );
-- 39 child tables hardened: academic_calendar, activity_logs, assignment_submissions, assignments, attendance, attendance_modes, complaints, daily_attendance, doubt_messages, employee_attendance, exam_results, exam_subjects, fee_components, fee_payments, helpdesk_comments, hostel_room_allocations, hostel_rooms, leaves, library_issues, mcq_answers, mcq_questions, mcq_submissions, parent_messages, parent_students, payments, performance_reviews, refresh_tokens, refunds, route_stops, student_scholarships, study_materials, subject_allocations, subject_attendance, timetable_entries, user_notifications, vehicle_inspections, vehicle_maintenances, vehicle_routes, workflow_actions
-- skipped (no tenant anchor): Institution (tenant root), SubscriptionPlan (no tenant-anchored FK chain), RolePricing (no tenant-anchored FK chain), Charge (no tenant-anchored FK chain)
