import * as fs from 'fs';
import * as path from 'path';
import { CHILD_POLICIES, CHILD_SKIPPED, TENANT_GUC } from '../config/tenant-chain';

// Phase 6b: RLS for child tables (models without institutionId). The policy
// walks the FK chain to a tenant anchor (see config/tenant-chain.ts), e.g.
//   mcq_answers."submissionId" IN (SELECT id FROM mcq_submissions
//       WHERE testId IN (SELECT id FROM mcq_tests WHERE institutionId = <tenant>))
// Same permissive semantics as the Phase 5 policies: GUC unset/empty
// (CEO, scripts, migrations) → unrestricted; GUC set → parent chain must
// resolve to that institution for both reads (USING) and writes (WITH CHECK).

const POLICY = (table: string, expr: string) => `
ALTER TABLE "public"."${table}" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."${table}" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON "public"."${table}";
CREATE POLICY "tenant_isolation" ON "public"."${table}"
  FOR ALL
  USING (
    ${TENANT_GUC} IS NULL
    OR (${expr})
  )
  WITH CHECK (
    ${TENANT_GUC} IS NULL
    OR (${expr})
  );`;

const sql = `-- Phase 6b: row-level security for child tables (no institutionId column).
-- Generated by src/scripts/gen-rls-child-migration.ts — do not hand-edit;
-- regenerate if the schema's parent chains change.
-- Requires the Phase 5 migration (20260928000000_rls_tenant_isolation) and the
-- \`erp_app\` role. Grants were already issued for ALL TABLES in Phase 5.
${CHILD_POLICIES.map((p) => POLICY(p.table, p.expr)).join('\n')}
-- ${CHILD_POLICIES.length} child tables hardened: ${CHILD_POLICIES.map((p) => p.table).join(', ')}
-- skipped (no tenant anchor): ${CHILD_SKIPPED.map((s) => `${s.model} (${s.reason})`).join(', ')}
`;

const dir = path.join(__dirname, '../../prisma/migrations/20260928000100_rls_child_isolation');
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'migration.sql'), sql);
console.log(`wrote ${CHILD_POLICIES.length} child policies to ${dir}`);
console.log('tables:', CHILD_POLICIES.map((p) => p.table).join(', '));
console.log('skipped:', CHILD_SKIPPED.map((s) => `${s.model} (${s.reason})`).join(', '));
